### ISSUE TITLE
This should fix the setup-serverless action error

### ISSUE THREAD

**Issue by Teakowa** [Aysnine/my-serverless-graphql-app#1]
Hello Aysnine,

Thank you for using my action, I noticed that you are experiencing some issues that are preventing the action not working.

```yml
- uses: Teakowa/setup-serverless@v2.0.0
  with:
    provider: tencent
    serverless_version: 2.4.0
  env:
    TENCENT_APPID: ${{ secrets.TENCENT_APP_ID }}
    TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
    TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY}}
    TENCENT_TOKEN: ${{ secrets.TENCENT_TOKEN}}
```

If you are using Tencent Cloud Global, this shouldn't be a problem.

But if you are using Tencent Cloud China, this will not work, Because an important environment variable is missing.

```yml
- uses: Teakowa/setup-serverless@v2.0.0
  with:
    provider: tencent
    serverless_version: 2.4.0
  env:
    TENCENT_APPID: ${{ secrets.TENCENT_APP_ID }}
    TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
    TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY}}
    SERVERLESS_PLATFORM_VENDOR: tencent # Must be set here to use in China
```

`SERVERLESS_PLATFORM_VENDOR` must be set to `tencent`, only then will action be configured to use Chinese guide and to enable network acceleration outside of China.
(you can see https://cloud.tencent.com/document/product/1154/50938#.E5.B8.B8.E8.A7.81.E9.97.AE.E9.A2.98)

As well, you don't need to set the `TENCENT_TOKEN` variable because the action doesn't support it at the moment xD

I've updated this to the action documentation([README](https://github.com/Teakowa/setup-serverless/blob/2.x/README.md#tencent-cloud)), hope it helps you. 😊

If you have any questions, feel free to reply to me
